### PR TITLE
Add Python 3.12 and Python 3.13 to build

### PR DESCRIPTION
**Pull request by SteveGrehl**

### CODE REVIEW

**Review by RLumSK — COMMENTED** [review]
Thanks @SteveGrehl it looks good to me.

**Comment by SteveGrehl** [comment]
See discussions:
https://github.com/s-weigand/setup-conda/issues/432
https://github.com/actions/runner-images/issues/9262#issuecomment-1918858684

**Comment by SteveGrehl** [comment]
@RLumSK pipelines are now green, we can deploy

**Review by RLumSK — APPROVED** [review]
@SteveGrehl Thanks once more for keeping this up-to-date!

**Pull request merged**
